### ISSUE TITLE
Draft message

### ISSUE THREAD

**Issue by juanxupalaci** [DarshanParbadiya/WhatsApp-Automation-Bulk-Messages-Images-Sender#2]
Hi,

I have tried the "Send text message only" option with an excel file with 2 rows, and the messages are written on WhatsApp web but it does not send them (leave messages as drafts)

Regards.

**Comment by juanxupalaci** [comment]
You have to modify line 446 with the following code:

(By.XPATH, "//button[@data-tab='11']")))

Regards.

**Comment by DarshanParbadiya** [comment]
Yes you are right, just open whatsapp web and change that line according to
the ui, may be whatsapp web has changed some tags thats why it is not
working, i will change it when i am free

**Comment by AdamChikh** [comment]
> You have to modify line 446 with the following code:
> 
> (By.XPATH, "//button[[@Data-TAB](https://github.com/Data-TAB)='11']")))
> 
> Regards.

Hello mate i use parrote os i change same line but it's doesn't work i have same problem the message stay on draft can u please help
