### ISSUE TITLE
Excel file not generating for contact upload

### ISSUE THREAD

**Issue by abhishek7791** [DarshanParbadiya/WhatsApp-Automation-Bulk-Messages-Images-Sender#4]
Excel file not generating for contact upload

**Comment by DarshanParbadiya** [comment]
Brother, i dont have enough time to check and solve this problem. The code
is open source, you can find bugs and solve the problem.
If I get any time I wil fix that issue.

**Comment by DarshanParbadiya** [comment]
This is fixed in the new release.
